### PR TITLE
Math2d and math3d features

### PR DESCRIPTION
**Pull request by UbuntuJackson**
Bundles with Math2d and Math3d features in pure C++

Important contents are the math2d folder, the math3d folder, and the test folders. Everything else is misc and we can discuss
how much of that we wanna keep.

math2d is a bundle with a Vector2 class, a Ray2 class which builds on the Vector2 class, and a ray Intersection class.
The importance of collision_info.hpp is not to be underestimated, we need to return as much information as necessary.
Usecase for these features: Any collision that requires more accuracy and predictability. Any detection where using a rectangle or circle for detection would be excessive. We can also build heavily on these features.

math3d is very work in progress, and I am having a little trouble formatting the matrices. We can scrap it, but keeping it would allow for more people to work on it. Since I tried my best formatting the code, I'd say it can be improved from here.

The test projects. I suggest we touch them up a little and keep them for people to use as they develop further on these features.

I lowkey think we should keep the other things too for the moment as they might be powerful if done correctly. Let's discuss those properly too.

### CODE REVIEW

**Review by hexaheximal — CHANGES_REQUESTED** [review]
This PR contains auto-generated build files (don't do that) and is on the stable branch (don't do that either).

You should close this PR, delete your existing remote branch, add the relevant changes to a new branch based on unstable, and then create a new PR.

**Comment by UbuntuJackson** [comment]
> This PR contains auto-generated build files (don't do that) and is on the stable branch (don't do that either).
> 
> You should close this PR, delete your existing remote branch, add the relevant changes to a new branch based on unstable, and then create a new PR.

How do I know that it is in fact on the stable branch? Second, it IS based on unstable, as I modified the unstable one.
I also had to fork brux in order to do a pull request, in case that fact has any relevance.

**Comment by hexaheximal** [comment]
> > This PR contains auto-generated build files (don't do that) and is on the stable branch (don't do that either).
> > You should close this PR, delete your existing remote branch, add the relevant changes to a new branch based on unstable, and then create a new PR.
> 
> How do I know that it is in fact on the stable branch? Second, it IS based on unstable, as I modified the unstable one. I also had to fork brux in order to do a pull request, in case that fact has any relevance.

You're trying to merge into master, which is the stable branch.

**Comment by UbuntuJackson** [comment]
> > How do I know that it is in fact on the stable branch? Second, it IS based on unstable, as I modified the unstable one. I also had to fork brux in order to do a pull request, in case that fact has any relevance.
> 
> You're trying to merge into master, which is the stable branch.
> 
> EDIT: it's also worth noting that your branch appears to be based on an older version of the unstable branch.

Be more clear about what you want me to do about that, cause this version is not like, insanely old.

**Comment by UbuntuJackson** [comment]
> > How do I know that it is in fact on the stable branch? Second, it IS based on unstable, as I modified the unstable one. I also had to fork brux in order to do a pull request, in case that fact has any relevance.
> 
> You're trying to merge into master, which is the stable branch.
> 
> EDIT: it's also worth noting that your branch appears to be based on an older version of the unstable branch.

I actually cloned it a few weeks ago. So what can possibly have gone wrong if it's older than that?

**Comment by hexaheximal** [comment]
I think you're overthinking this too much.

You're trying to merge an older version of the unstable branch, now with a new commit, into the stable branch. Doing that will break the commit history and cause a conflict mess.

And again, you're including auto-generated build files in your commit. Don't do that. They are not meant to be committed to the repository.

**Comment by UbuntuJackson** [comment]
Closing with comment.

**Pull request closed without merging**
