### PR TITLE
rte/Makefile: Less hardcoding + proper rules

### PR DESCRIPTION
**Pull request by lanodan**
- rte/makefile: Add bin/brux* targets to clean
- rte/Makefile: Less hardcoding + proper rules

### CODE REVIEW

**Comment by KelvinShadewing** [comment]
I'm still not very versed with makefiles and only threw together what worked from a starter tutorial. Would you be willing to explain these changes?

**Comment by lanodan** [comment]
>I'm still not very versed with makefiles and only threw together what worked from a starter tutorial. Would you be willing to explain these changes?

I partially did in the commit messages, feel free to ask questions about each part.

Errors I didn't note in it were:
- CXXFLAGS (C++) vs. CFLAGS (C)
- Putting C(XX)FLAGS and defines at the end of c++ arguments, might not be much of a problem, $(LIBS) is the one I know is positional
- C(XX)FLAGS should only contain user-overridable flags like `-O2 -g` so developers and packagers can use their own, this is what makes the debug target potentially obsolete

**Comment by KelvinShadewing** [comment]
Oh, I see. I was mainly wondering at the removal of CFLAGS. Does using CXXFLAGS instead have some sort of effect?

**Comment by lanodan** [comment]
[2023-01-14 14:53:59-0800] Kelvin Shadewing:
>Oh, I see. I was mainly wondering at the removal of CFLAGS. Does using CXXFLAGS instead have some sort of effect?

Well, CXXFLAGS is for C++, CFLAGS is for C. And in some cases the difference matters as there is C specific flags and C++ specific flags.

**Comment by tulpenkiste** [comment]
Given PR #50 (specifically commit 5500b25), this PR probably won't work anymore (due to the removal of rte/Makefile).

**Pull request closed without merging**
