### PR TITLE
Improvements to IDE

### PR DESCRIPTION
**Pull request by tulpenkiste**
The following changes have been made to the IDE:

- `.h` changed to `.hpp`
- Used better coding style
- [LINUX ONLY] Introduce mimetypes for squirrel files and brux main scripts
- Changes to KSyntaxHighlighting
- Test Project button
- Removed tiled dependency

### CODE REVIEW

**Review by hexaheximal — CHANGES_REQUESTED** [review]
It looks like you forgot to upload your GPG pubkey.

**Comment by tulpenkiste** [comment]
Oh nah, I do have mine connected. GitHub is just stupid

**Comment by hexaheximal** [comment]
It's not *that* hard, you just need to go to https://github.com/settings/keys and paste in the pubkey text.

**Comment by tulpenkiste** [comment]
I had it set up, it just didn't work lol

**Pull request merged**
